### ISSUE TITLE
100% CPU usage by container mailserver

### ISSUE THREAD

**Issue by epa64** [mailserver2/mailserver#32] opened 2021-01-14 17:20 UTC
#### Classification
* [X] Question

Hi, my mail server version is v1.1 (old hardware/mailserver) i never migrate since 2 years.
The mailserver container is up to 100% cpu usage.
The hardware CPU ( cat /proc/info) configuration is : 2 X Intel(R) Atom(TM) CPU  330   @ 1.60GHz ( 4 Thread ).
Docker stats 
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
     
63d654e97f21        rainloop            0.01%               10.14MiB / 1.935GiB   0.51%               1.5kB / 0B          14.7MB / 32.8kB     9
805f5ba5b172        postfixadmin        0.01%               7.762MiB / 1.935GiB   0.39%               1.5kB / 0B          12.2MB / 4.1kB      2
**b00ca4969d77        mailserver          102.50%**             521MiB / 1.935GiB     26.29%              3.77MB / 1.41MB     492MB / 6.38MB      85
77f28a0111f6        traefik             0.03%               16.3MiB / 1.935GiB    0.82%               546B / 0B           55.8MB / 0B         14
f416fceebd91        redis               0.29%               45.3MiB / 1.935GiB    2.29%               369kB / 6.18MB      36.3MB / 102kB      4
4accb0581ba7        mariadb             0.16%               68.09MiB / 1.935GiB   3.44%               57.4kB / 45.3kB     48.8MB / 4.19MB     39
```
The htop command show 1 thread > 100%.
it is possible in docker-compose 3 to assigns 3 thread in this container ?
Have you a other solution ?

Best regard's
Eric

**Comment by sknight80** [comment] 2021-01-15 16:25
I only have this issue when my mail server (still running on the old hardware mail config) got about ~100 emails per second (Amazon SNS notifications).  Afterward, it is going back to normal around ~30-40% usage.  @AndrewSav or @SaraSmiseth did you noticed anything like this?

**Comment by SaraSmiseth** [comment] 2021-01-16 07:17
Everything is fine for me. No high CPU usage.

**Comment by AndrewSav** [comment] 2021-01-16 10:17
Haven't seen high CPU usage.

**Comment by AndrewSav** [comment] 2021-03-05 02:27
@epa64 Since you are saying that you have not upgraded in the last two years, this could be something I'd recommend first. Since we cannot reproduce this, and the project is in the minimal maintenance mode, I'm going to close this, because it is not clear what we can do here, and therefore it is unlikely this it will be resolved by us. Having said that, if you have anything else in mind with regards to this issue, please feel free to write back, and if there is anything else we can help with, we can re-open it.

**Closed by AndrewSav** 2021-03-05 02:27 UTC

**Comment by epa64** [comment] 2021-03-05 08:27
Sorry,

The problem was related to a lack of swap on the server.

Best regards


Le 05/03/2021 à 03:28, Andrew Savinykh a écrit :
